# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 681a87f41ca1ea9f4a82ac6a50fde27adec9c7ad623c46fd81d81409725fafdb4d8719f648b63bde6d39aa475a9bb43ed7eabe37a6ddbc93a2eb99e5d25e661f

test:
  secret_key_base: 9749d99251f999ee188e88ce83a799939133b64571ba6cee70c8422619ff9c43044c61920167aa78f09115f1cf9eaf4a0bbab05b36ee7d4134aece244ebdd98d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
